stages:
  - build
  - test
  - coverage
  - deploy

node-dependencies:
  stage: build
  script: "npm install"
  artifacts:
    paths:
    - node_modules/

check-js-code-style:
  stage: test
  script: "npm run jscs"
  dependencies:
    - node-dependencies

get-js-code-coverage:
  stage: coverage
  script:
    - "test-assets/docker/docker-mysql-unit-tests.sh start"
    - "istanbul cover ./node_modules/mocha/bin/_mocha --no-colors"
    - "test-assets/docker/docker-mysql-unit-tests.sh stop"
  dependencies:
    - node-dependencies

deploy-dev:
    stage: deploy
    only:
    - master
    script: "rsync -r . ubuntu@146.108.214.6:/var/www/api --exclude '*.git'"
